<?php

namespace simialbi\yii2\schemaorg\models;

/**
 * A Report generated by governmental or non-governmental organization.
 *
 * @package simialbi\yii2\schemaorg\models
 * @see http://schema.org/Report
 */
class Report extends Article {
    /**
     * The number or other unique designator assigned to a Report by the publishing
     * organization.
     *
     * @var string
     */
    public $reportNumber;


}